# Generated by Django 3.1.7 on 2021-05-09 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSupra', '0002_auto_20210509_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appSupra.areas'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appSupra.documento'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appSupra.sub_areas'),
        ),
        migrations.AlterField(
            model_name='sub_areas',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appSupra.areas'),
        ),
    ]
