# Generated by Django 3.1.7 on 2021-05-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSupra', '0004_auto_20210509_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('apellido', models.CharField(max_length=300)),
                ('numeroDocumento', models.BigIntegerField()),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appSupra.areas')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appSupra.documento')),
                ('subarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appSupra.sub_areas')),
            ],
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
    ]
